import iris
from pathlib import Path

SUITES = {"wasp96b" : {
              "equilibrium" : { 
                  "solar" : {
                      "planet" : "wasp96b",
                      "suite" : "u-cp158",
                      "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                      "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                      "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ.ncdf",
                      "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ.ncdf",
                      "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_sw_500",
                      "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_lw_500",
                      "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day",
                      "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night",
                      "dir_for_transmission_day_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_nh3",
                      "dir_for_transmission_night_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_nh3",
                      "dir_for_transmission_day_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_ch4",
                      "dir_for_transmission_night_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_ch4",
                      },
                  "10xsolar" : {
                      "planet" : "wasp96b",
                      "suite" : "u-cp770",
                      "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp770"/"raw",
                      "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                      "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ_MdH1.ncdf",
                      "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ_MdH1.ncdf",
                      "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh1_sw_500",
                      "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh1_lw_500",
                      "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp770"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day",
                      "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp770"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night",
                      #"dir_for_transmission_day_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp770"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_nh3",
                      #"dir_for_transmission_night_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp770"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_nh3",
                      #"dir_for_transmission_day_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp770"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_ch4",
                      #"dir_for_transmission_night_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp770"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_ch4",
                      },
                  "C_Scale" : {
                      "planet" : "wasp96b",
                      "suite" : "u-cp158",
                      "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                      "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                      "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ_scale_carbon.ncdf",
                      "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ_scale_carbon.ncdf",
                      "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_sw_500",
                      "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_lw_500",
                      "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                      "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                      },
                  "O_Scale" : {
                      "planet" : "wasp96b",
                      "suite" : "u-cp158",
                      "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                      "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                      "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ_scale_oxygen.ncdf",
                      "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ_scale_oxygen.ncdf",
                      "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_sw_500",
                      "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_lw_500",
                      "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                      "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                      },
                  },
             "kinetics" : {
                 "solar" : {
                     "planet" : "wasp96b",
                     "suite" : "u-cp238",
                     "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw",
                     "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                     "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ.ncdf",
                     "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ.ncdf",
                     "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_sw_500",
                     "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_lw_500",
                     "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day",
                     "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night",
                     "dir_for_transmission_day_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_nh3",
                     "dir_for_transmission_night_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_nh3",
                     "dir_for_transmission_day_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_ch4",
                     "dir_for_transmission_night_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_ch4"
                     },
                 "10xsolar" : {
                      "planet" : "wasp96b",
                      "suite" : "u-cp805",
                      "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp805"/"raw",
                      "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                      "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ_MdH1.ncdf",
                      "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ_MdH1.ncdf",
                      "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh1_sw_500",
                      "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh1_lw_500",
                      "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp805"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day",
                      "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp805"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night",
                      "dir_for_transmission_day_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp805"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_nh3",
                      "dir_for_transmission_night_NH3": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp805"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_nh3",
                      "dir_for_transmission_day_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp805"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_day_ch4",
                      "dir_for_transmission_night_CH4": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp805"/"raw"/"atmos_base_1001"/"atmosa.ph0000001000_00_night_ch4",
                      },
                 "C_Scale" : {
                     "planet" : "wasp96b",
                     "suite" : "u-cp158",
                     "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw",
                     "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                     "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ_scale_carbon.ncdf",
                     "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ_scale_carbon.ncdf",
                     "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_sw_500",
                     "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_lw_500",
                     "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                     "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                     },
                 "O_Scale" : {
                     "planet" : "wasp96b",
                     "suite" : "u-cp158",
                     "dir_for_raw": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"kinetics"/"u-cp238"/"raw",
                     "dir_for_merged": Path.home()/"um"/"um_runs"/"merged",
                     "initial_pt_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_PT_EQ_scale_oxygen.ncdf",
                     "initial_chem_profile_file": Path.home()/"atmo"/"practice"/"WASP-96b"/"WASP-96b_Chem_EQ_scale_oxygen.ncdf",
                     "dir_for_star_spectrum_sw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_sw_500",
                     "dir_for_star_spectrum_lw": Path.home().parent.parent/"data"/"dc605"/"For_WASP-96b_Students"/"spec_file_wasp96b_mdh0_lw_500",
                     "dir_for_transmission_day_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                     "dir_for_transmission_night_total": Path.home().parent.parent/"data"/"mz355"/"um_runs"/"wasp96b"/"equilibrium"/"u-cp158"/"raw",
                     },
                 },
  },
}

PLANETS = {
    "wasp96b": {"tex": "WASP-96b"},
}


GASES = {
    "He": {"tex": "$He$", "color": "C4"},  # needs changing (C4 as HCN)
    "CH3": {"tex": "$CH_3$"},
    "H": {"tex": "$H$", "color": "C9"},
    "1CH2": {"tex": "$^{1}CH_2$"},
    "H2": {"tex": "$H_2$", "color": "C0"},  # needs changing (C0 as H2O)
    "CH4": {
        "molar_mass": iris.cube.Cube(
            16.043, units="g mol-1", long_name="CH4 molar mass"
        ),
        "tex": "$CH_4$",
        "color": "C3",
    },
    "O-3P": {"tex": "$O(^{3}P)$"},
    "OH": {"tex": "$OH$"},
    "CO": {
        "molar_mass": iris.cube.Cube(28.010, units="g mol-1", long_name="CO molar mass"),
        "tex": "$CO$",
        "color": "C1",
        "name": "CO",
    },
    "3CH2": {"tex": "$^{3}CH_2$"},
    "H2CO": {"tex": "$H_2CO$"},
    "CH3O": {"tex": "$CH_3O$"},
    "H2O": {
        "molar_mass": iris.cube.Cube(
            18.015, units="g mol-1", long_name="H2O molar mass"
        ),
        "tex": "$H_2O$",
        "color": "C0",
    },
    "CH3OH": {"tex": "$CH_3OH$"},
    "CO2": {
        "molar_mass": iris.cube.Cube(
            44.009, units="g mol-1", long_name="CO2 molar mass"
        ),
        "tex": "$CO_2$",
        "color": "C2",
    },
    "HCO": {"tex": "$HCO$"},
    "CH2OH": {"tex": "$CH_2OH$"},
    "NH": {"tex": "$NH$"},
    "NNH": {"tex": "$NNH$"},
    "N2": {"tex": "$N_2$", "color": "C7"},
    "NH2": {"tex": "$NH_2$"},
    "N2H2": {"tex": "$N_2H_2$"},
    "NH3": {
        "molar_mass": iris.cube.Cube(
            17.031, units="g mol-1", long_name="NH3 molar mass"
        ),
        "tex": "$NH_3$",
        "color": "C5",
    },
    "N2H3": {"tex": "$N_2H_3$"},
    "HOCN": {"tex": "$HOCN$"},
    "NCO": {"tex": "$NCO$"},
    "CN": {"tex": "$CN$"},
    "HCN": {
        "molar_mass": iris.cube.Cube(
            27.025, units="g mol-1", long_name="HCN molar mass"
        ),
        "tex": "$HCN$",
        "color": "C4",
    },
    "HNCO": {"tex": "$HNCO$"},
    "H2CN": {"tex": "$H_2CN$"},
}


STASH = {
    #"tendency_of_air_temperature_due_to_longwave_heating": "tendency_of_air_temperature_due_to_longwave_heating",
    #"tendency_of_air_temperature_due_to_shortwave_heating": "tendency_of_air_temperature_due_to_shortwave_heating",
    "x_wind": "x_wind",
    "y_wind": "y_wind",
    "upward_air_velocity": "upward_air_velocity",
    #"air_potential_temperature": "air_potential_temperature",
    "air_pressure": "air_pressure",
    "air_temperature": "air_temperature",
    "toa_incoming_shortwave_flux": "toa_incoming_shortwave_flux",
    "toa_outgoing_longwave_flux": "toa_outgoing_longwave_flux",
    "toa_outgoing_shortwave_flux": "toa_outgoing_shortwave_flux",
    #"m01s00i253": "DENSITY*R*R AFTER TIMESTEP",
    #"dimensionless_exner_function": "dimensionless_exner_function",
    #"surface_air_pressure": "surface_air_pressure",
    #"surface_temperature": "surface_temperature",
    "m01s56i001": "H mole fraction",
    "m01s56i002": "OH mole fraction",
    "m01s56i003": "CH3 mole fraction",
    "m01s56i004": "H2CO mole fraction",
    "m01s56i005": "O-3P mole fraction",
    "m01s56i006": "NH2 mole fraction",
    "m01s56i007": "H2 mole fraction",
    "m01s56i008": "CO mole fraction",
    "m01s56i009": "H2O mole fraction",
    "m01s56i010": "HCO mole fraction",
    "m01s56i011": "NH mole fraction",
    "m01s56i012": "HCN mole fraction",
    "m01s56i013": "CH3OH mole fraction",
    "m01s56i014": "CH4 mole fraction",
    "m01s56i015": "CH3O mole fraction",
    "m01s56i016": "NCO mole fraction",
    "m01s56i017": "CH2OH mole fraction",
    "m01s56i018": "N2H2 mole fraction",
    "m01s56i019": "NH3 mole fraction",
    "m01s56i020": "NNH mole fraction",
    "m01s56i021": "CN mole fraction",
    "m01s56i022": "HNCO mole fraction",
    "m01s56i023": "3CH2 mole fraction",
    "m01s56i024": "N2 mole fraction",
    "m01s56i025": "N2H3 mole fraction",
    "m01s56i026": "1CH2 mole fraction",
    "m01s56i027": "HOCN mole fraction",
    "m01s56i028": "H2CN mole fraction",
    "m01s56i029": "CO2 mole fraction",
    "m01s56i030": "He mole fraction",
    #'m01s01i755' : 'TRANSMISSION SPECTRUM 2nd CALL',
    #'m01s02i713' : 'LW EMISSION SPECTRUM 2nd CALL',
}